spring:
  application:
    name: bank
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: "${FAJBANK_USERNAME_DATABASE}"
    password: "${FAJBANK_PASSWORD_DATABASE}"
    url: jdbc:mysql://localhost:3306/fajbank?useTimezone=true&serverTimezone=UTC

  flyway:
    baseline-on-migrate: true
    enabled: false
    locations: classpath:db/migration

jwt:
  secret: "${JWT_SECRET_FAJBANK}"
  public: root

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    filter: true