import auth.http

### Criar transação com cartão de crédito
POST http://localhost:8080/v1/checkout/create
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
    "invoice_id": 1,
    "payment_method_id": 1,
    "payment_type": "CREDIT_CARD"
}

### Consultar status do checkout
GET http://localhost:8080/v1/checkout/status/2
Authorization: Bearer {{auth_token}}

### Cancelar checkout
PUT http://localhost:8080/v1/checkout/cancel/2
Authorization: Bearer {{auth_token}}

### Confirmar pagamento
PUT http://localhost:8080/confirm-payment/1
Authorization: Bearer {{auth_token}}
