import auth.http

### Register a new payment method
POST http://127.0.0.1:8080/v1/wallet/register-payment-method
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "cardNumber": "11111111111",
  "cardHolderName": "John Doe",
  "expirationDate": "12/25",
  "cvv": "123"
}

### GET All payment method
GET http://127.0.0.1:8080/v1/wallet
Content-Type: application/json
Authorization: Bearer {{auth_token}}

### DELETE payment method
POST http://127.0.0.1:8080/v1/wallet/remove/1
Content-Type: application/json
Authorization: Bearer {{auth_token}}